declare const Koa: any;
declare const bodyParser: any;
declare const userRouter: any;
declare const nunjucks: any;
declare const path: any;
declare const cors: any;
declare const koaJwt: any;
declare const config: any;
declare const app: any;
