declare const _joi: any;
declare const menuTitle: any;
declare const menuDescription: any;
declare const _img: any;
declare const _id: any;
declare const _pid: any;
declare const _idNotRequired: any;
declare const addMenuSchema: any;
declare const editMenuSchema: any;
